# Generated by Django 3.2.4 on 2021-06-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_obra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(upload_to='obras', verbose_name='Imagen'),
        ),
    ]
