# Generated by Django 3.2.4 on 2021-06-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=40, verbose_name='Nombre de la obra')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
                ('precio', models.CharField(max_length=9, verbose_name='Precio ($CLP)')),
                ('tipo_obra', models.CharField(max_length=20, verbose_name='Tipo de obra')),
                ('alto', models.CharField(max_length=4, verbose_name='Alto')),
                ('ancho', models.CharField(max_length=4, verbose_name='Ancho')),
                ('largo', models.CharField(max_length=4, verbose_name='largo')),
                ('soporte', models.CharField(max_length=20, verbose_name='Soporte')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='proyects', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
