# Generated by Django 3.2.3 on 2021-06-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(max_length=80, verbose_name='Nombre del artista')),
                ('especialidad_artista', models.CharField(max_length=80, verbose_name='Especialidad')),
                ('biografia', models.TextField(max_length=250, verbose_name='Biografía')),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('foto_perfil', models.ImageField(upload_to='artistas', verbose_name='Foto de perfil')),
            ],
        ),
    ]
