# Generated by Django 3.2.4 on 2021-06-25 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditarPerfil',
            fields=[
                ('nombre_artista', models.CharField(max_length=80, verbose_name='Nombre del artista')),
                ('rut_artista', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut (sin puntos ni guion)')),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('biografia', models.TextField(max_length=250, verbose_name='Biografía')),
                ('foto_perfil', models.ImageField(upload_to='artistas', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=40, verbose_name='Nombre de la obra')),
                ('anio', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')], verbose_name='Año')),
                ('precio', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')], verbose_name='Precio ($CLP)')),
                ('tipo_obra', models.CharField(max_length=100, verbose_name='Tipo de obra')),
                ('alto', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')], verbose_name='Alto (cm)')),
                ('ancho', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')], verbose_name='Ancho (cm)')),
                ('largo', models.CharField(max_length=4, verbose_name='largo (cm)')),
                ('soporte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Soporte (opcional)')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='obras', verbose_name='Imagen')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artista.editarperfil')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
