# Generated by Django 3.2.4 on 2021-06-21 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_auto_20210621_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='alto',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')], verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='ancho',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')], verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='largo',
            field=models.CharField(max_length=4, verbose_name='largo (cm)'),
        ),
    ]
